fix problem when the table name is not quoted and there is more than …
schemaspy/schemaspy pull request #794
Opened 2021-09-29 06:18 UTC by DanNYSPD

## Description 
Fixes the  problem when the table name is not quoted and there is more than one table name with same characters but different case, also I add the tablename in the message of InconsistencyException for error report purposes

## Expected Behavior

When there are two tables (or more) with the same characters but different case it must be able to avoid confussion among all this tables. 
For example, in postgres the table user and "User" are different tables (is case sensitive) so is necessary to use quotes to avoid confusion when making queries in a linux/unix Server. When you query <select * from user> is not the same to <select * from "User"> in a linux environment. (note that I use angle brackets to simplify the use of quotes)

At least a more detailed message is expected.

## Current Behavior
When there are this two tables and InconsistencyException exception is thrown when a column is not found in the column of the table object. Besides no table name is provided in the current exception message.

src/main/java/org/schemaspy/input/dbms/service/ColumnService.java
`throw new InconsistencyException("Column information from DatabaseMetaData differs from ResultSetMetaData, expected to find column named: '"+ columnName + "' in " + listColumns(table));`

`throw new InconsistencyException("Column information from DatabaseMetaData differs from ResultSetMetaData, expected to find column named: '"+ columnName + "' in columns" + listColumns(table) +" of table: "+tableName);` 

## Possible Solution
This PR adds more info in the exception message(return the table name) and fix the problem by setting the flag forceQuotes to true.

## Context

* Database type: Postgres 
*  Command is showed below:
~~~bash
java -jar schemaspy-6.1.0.jar -t pgsql -dp $DP -db $DATABASE -host $SERVER -port $PORT -s public -u $USER -p $PASSWORD -o $DIRECTORY
~~~

## Your Environment
* Fedora 34
* JAVA 11

2021-09-29 06:19 UTC, DanNYSPD commented on src/main/java/org/schemaspy/input/dbms/service/ColumnService.java
> +        String tableName=sqlService.getQualifiedTableName(
Store the qualified table name to use both in the sql and in the exception message

2021-09-29 06:19 UTC, DanNYSPD commented on src/main/java/org/schemaspy/input/dbms/service/ColumnService.java
> +                    throw new InconsistencyException("Column information from DatabaseMetaData differs from ResultSetMetaData, expected to find column named: '"+ columnName + "' in columns" + listCol
improved message detail

2021-12-11 13:31 UTC, rafalkasa commented
This PR is ok for me and can be merged if small line will be corrected

2021-12-24 00:15 UTC, npetzall commented
> This PR is ok for me and can be merged if small line will be corrected

What needs correcting?

2021-12-24 01:10 UTC, rafalkasa commented
> @rafalkasa
> 
> > This PR is ok for me and can be merged if small line will be corrected
> 
> What needs correcting?

I'm referring to the comment with not used code 

`//LOGGER.info("SQL:"+sql.`

2021-12-24 01:41 UTC, npetzall requested changes

2021-12-24 01:41 UTC, npetzall commented on src/main/java/org/schemaspy/input/dbms/service/ColumnService.java
> +        //LOGGER.info("SQL:"+sql.toString());
Remove this comment

2022-05-30 20:48 UTC, npetzall approved these changes

2022-05-30 22:45 UTC, merged