Refactoring
schemaspy/schemaspy pull request #924
Opened 2022-06-17 10:51 UTC by jesperolsson-se

2022-06-17 13:07 UTC, npetzall requested changes
ProgressListener is bad, most of the methods that "render"/write to console har only invoked if Html.
So ConsoleProgressListener doesn't do anything with the console except for 1 method that has something to do with exceptions.

Two things that could be done, 
1. skip the whole if htmlEnabled. It will almoste never be called if it's disabled. Has more with verbose than html, but only used when doing html. Strange stuff.

But the responsibilities could be divided. 
ConsoleProgressListener.java -> Tracked.java
Html -> Console.java

2022-06-17 13:10 UTC, npetzall commented on src/main/java/org/schemaspy/model/ConsoleProgressListener.java
> +    public String recoverableExceptionEncountered(String msg, Exception exc, String sql) {
Remove, this isn't progress, it not used, but declared by the interface.

2022-06-17 13:11 UTC, npetzall commented on src/main/java/org/schemaspy/model/ConsoleProgressListener.java
> +    public ConsoleProgressListener() {
Doesn't do much with "Console", should Tracking, Timing, or Simple, Base

2022-06-17 13:13 UTC, npetzall commented on src/main/java/org/schemaspy/model/Html.java
> +public class Html implements ProgressListener {
Most methods are used by Html generating Code. But what it does is write to System.out which in it self isn't great.

System.out is StdOut so may be StdOut or Console.

2022-06-17 13:13 UTC, npetzall commented on src/main/java/org/schemaspy/model/Html.java
> +    public String recoverableExceptionEncountered(String msg, Exception exc, String sql) {
Should be removed from interface and thus from here.

2022-06-17 14:51 UTC, jesperolsson-se reviewed
The review comments are about pre-existing implementation. I'd be happy to resolve them in new PRs (after this one is merged). Do you have any concerns regarding the refactoring?

2022-06-17 15:54 UTC, npetzall commented
The naming issue is introduced.

2022-06-19 17:46 UTC, npetzall approved these changes

2022-06-19 17:46 UTC, merged

2022-06-22 19:15 UTC, npetzall commented
The removal is mentioned in #247